# RERO
# - 0.0.1 Beta
# :)
# >>--------------------------------------------------------------<<
# Name this file 'settings.yaml' and replace the following with your
# own token
BOT_TOKEN: "Your_Key_Goes_Here"

# Example prefix: &, *, ?, $ etc
PREFIX: ">"

# Your REDIS Passsword goes here. Rero won't work without REDIS.
# If you want to run a copy of rero, you will need REDIS
REDIS_PASSWORD: "Your_Key_Goes_Here"

# MongoDB authentication Info
MONGO_USER_NAME: "Your_ID_Goes_Here"
MONGO_PASSWORD: "Your_Key_Goes_Here"
MONGO_DATABASE_NAME: "rero"

# Host Machine IP Address
VPS_IP_ADDRESS: "127.0.0.1:27017"

# IDs of users who are allowed to view and edit XP bans
XP_BLACKLIST_IDS:
- "1"
- "2"
- "3"

# We need the osu! Api Key to do osu related functions which are a
# core part of Rero
OSU_API_KEY: Your_Key_Goes_Here

# Need the Api Key for Tillerino to Fetch PP
TILLERINO_KEY: "Your_Key_Goes_Here"

# Your Imgur API Client ID
IMGUR_CLIENT_ID: "Your_ID_Goes_Here"

# MyAnimeList ID and password
MAL_ID: Your_ID_Goes_Here
MAL_PASSWORD: Your_Key_Goes_Here

# Danbooru ID and password
DANBOORU_ID: Your_ID_Goes_Here
DANBOORU_PASSWORD: "Your_Key_Goes_Here"

# Giphy API Key
GIPHY_API_KEY: "Your_Key_Goes_Here"

# Openweathermap App ID
OPENWEATHERMAP_APP_ID: "Your_Key_Goes_Here"

# YANDEX API Key (For translation)
YANDEX_API_KEY: "Your_Key_Goes_Here"
